flags: {}
extra-package-dbs: []
packages:
- .
- ../haskell-openzwave/haskell-openzwave
- ../haskell-openzwave/haskell-openzwave-cpp
- ../haskell-openzwave/haskell-openzwave-gen
- ../horizon
extra-deps:
- daemons-0.2.1
- hoppy-generator-0.3.4
- hoppy-runtime-0.3.2
- hoppy-std-0.3.0
- AC-Angle-1.0
resolver: lts-10.0 # ghc-8.2
